# Generated by Django 3.2.3 on 2021-05-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=32)),
                ('qnty', models.IntegerField()),
            ],
            options={
                'db_table': 'shop_list',
                'order_with_respect_to': 'qnty',
            },
        ),
    ]
