# Generated by Django 3.2.3 on 2021-05-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rel', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='shoppinglist',
            order_with_respect_to=None,
        ),
    ]
