# Generated by Django 3.2.3 on 2021-05-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rel', '0002_alter_shoppinglist_order_with_respect_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('id0', models.IntegerField()),
            ],
            options={
                'db_table': 'students',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('id0', models.IntegerField()),
                ('students', models.ManyToManyField(to='rel.Student')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
