# Generated by Django 3.2.3 on 2021-05-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rel', '0003_course_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('degree', models.CharField(choices=[('Dr', 'Doctor'), ('Prof', 'Doctor')], default='Dr', max_length=4)),
            ],
            options={
                'db_table': 'profs',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rel.professor'),
        ),
    ]
