# Generated by Django 3.2.3 on 2021-05-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rel', '0004_auto_20210524_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('title', models.CharField(max_length=32)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rel.student')),
            ],
            options={
                'db_table': 'diploma',
            },
        ),
    ]
